### ISSUE TITLE
Can't find cursor_data.csv

### ISSUE THREAD

**Issue by babai95** [yugrocks/follow_my_eye#1]
Hello Sir, I am unable to find cursor_data.csv as a result of which trainfloyd.py is not running.
Will you please tell me where to get it and also tell me what does cursor_data.csv contains?

**Comment by yugrocks** [comment]
Hi Sayantan. In order to train it, you first have to create data using the
script generate_data.py since I haven't uploaded the training data or the
model with it.

**Comment by babai95** [comment]
Sir, I executed the generate_data.py script and due to cursor = generate_data(), multiple images of my eye are stored in .\\Data\\eye_images\\ folder. But nothing is stored in cursor_data.csv, infact cursor_data.csv was not generated. how to generate cursor_data.csv so that i can access it in trainfloyd.py? 
labels = path_input+"cursor_data.csv"
    X = []
    y = []
    df = pd.read_csv(labels)
    labels = df.iloc[:, [1, 2]].values
in the above part error is coming as no cursor_data.csv was found

**Comment by yugrocks** [comment]
Okay, so the issue was I had accidently deleted some lines in generate_data.py before uploading. Now I have modified it, so cursor.csv will be created and stored in the required directory. And if you train it on your local computer, then use train.py. Use train_floydhub.py only if you are training it on floydhub cloud.
Now, for your information, the cursor.csv contains the x and y coordinates of the cursor such that each record is associated with some image of the eye in the eye_images. 
While creating the training data, try moving the cursor to wherever your eye focuses on your computer screen. Make sure to create a lot of training examples, by running it for at least 2-3 minutes.

**Comment by babai95** [comment]
Ok, so the previous issue was solved. Thanks a lot for that. But another issue has occured. In train.py, in load_data() method, in img=list(img.flatten()), an error has occured : 'NoneType' object has no attribute named flatten. I googled the error and found that such error occur mainly due to imread, i.e improper path of image given in imread. But the path  data/eye_images/eye_{}.jpg" seems to be fine. Then what could be the problem? Please help!!!

**Comment by yugrocks** [comment]
Okay, I got it. Actually when I edited the file generate_data.py, I had
changed the path to "data/.." which was "Data/.." before. And I noticed
that I had forgotten to update the same in train.py. Fixed this now.

**Comment by babai95** [comment]
Thanks a lot!!! now there are no more issues and the code is running successfully. Previously, the problem was that i=20600 but i should start from 0 as we are taking for i in range(len(y)) i.e i=0 to len(y). So initialise i with 0 and then everything is fine!
